site_name: sever
repo_url: https://github.com/JohnCoene/sever
site_description: Customise your Shiny disconnected screen and error messages.
site_author: John Coene
google_analytics: ['UA-74544116-1', 'sever.john-coene.com']
dev_addr: 'localhost:3000'
edit_uri: https://github.com/JohnCoene/sever/edit/master/docs/docs/
extra_css:
    - css/style.css
nav:
    - Home: index.md
    - User Guide: 
        - Sever: sever.md
        - Cleave: cleave.md
        - Examples: examples.md
    - Changelog: changelog.md
theme: 
  name: mkdocs
  hljs_style: dark
  highlightjs: true
  hljs_languages:
      - r
